### ISSUE TITLE
About train.txt and text.txt

### ISSUE THREAD

**Issue by yuehua-Song666** [ZiyuFanCSU/DGNNMDA#1]
Dear Authors,
Thank you so much for such a great work! 
I have a question here, when I was trying to run main.py, I found that "train.txt" and "test.txt" are missing. So I wonder where can I get them please?
Thank you so much.
Yuehua

**Comment by ZiyuFanCSU** [comment]
I am honored to receive your email. These two files are data set partitions, and the data is stored in github.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "19990915fzy/DGNNMDA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月17日(星期五) 上午10:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[19990915fzy/DGNNMDA] About train.txt and text.txt (Issue #1)





 
Dear Authors,
 Thank you so much for such a great work!
 I have a question here, when I was trying to run main.py, I found that "train.txt" and "test.txt" are missing. So I wonder where can I get them please?
 Thank you so much.
 Yuehua

**Comment by yuehua-Song666** [comment]
Thank you for your reply. Sorry I didn't understand clearly, can you please explain "These two files are data set partitions." please. Thank you.

**Comment by ZiyuFanCSU** [comment]
The file is divided based on the dataset using 5-fold cross-validation. The method can be found in the following link: https://blog.csdn.net/weixin_45961774/article/details/104868876.
