### ISSUE TITLE
train.txt

### ISSUE THREAD

**Issue by YINhang23** [ZiyuFanCSU/DGNNMDA#2]
你好，作者。
找不到train.txt and test.txt file.并且在代码中也没有看到生成的。方便发一下么？
邮箱：328525858@qq.com

**Comment by ZiyuFanCSU** [comment]
The file is divided based on the dataset using 5-fold cross-validation. The method can be found in the following link: https://blog.csdn.net/weixin_45961774/article/details/104868876.
